### ISSUE TITLE
Missing: Support for Create's Dough in FD recipes

### ISSUE THREAD

**Issue by sapphiriza** [22858/fdrfdcrf#1]
Hiya!
Thank you for making this compatibility layer!
I did notice there isn't an option for cutting Create's dough into noodles, or cooking it / using it in recipes that use FD's Wheat Dough. And vice versa, you can't use FD's Wheat Dough to craft recipes from Create, like vanilla Cake and Slimeballs.
Amusingly, it seems like End's Delight does add a Dough tag, but none of the recipes outside of End's Delight are updated to use the tag.

side-note: The ratio of water per dough is admittedly much higher for Create's Dough (1 bucket per 3 -> 1 bucket per 1), up to you how to handle that, I'd be happy with leaving it as-is. Using 1000mB water / dough does create downtime between each mix, but it's not that big of a deal, and you could mostly solve with ridiculous RPM anyway (or using an actual water bucket with the shapeless crafting recipe). Just a weird tangent

**Comment by 22858** [comment]
I'm not skilled in making a datapack, so it may take some time for me to do this😣
